#!/usr/bin/env bash

set -e

export CTEST_OUTPUT_ON_FAILURE=1

mkdir -p build
rm -rf ./build/*

(
    cd build/

    cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -G "Unix Makefiles" -DASAN=ON ..

    make

    make test
)

exit 0
